"""Initial migration

Revision ID: 997121b7f6fb
Revises: 
Create Date: 2026-05-16 12:08:29.999626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997121b7f6fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('patient', 'doctor', 'secretary', 'admin', name='userrole'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('doctors',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('crm', sa.String(length=20), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crm'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('patients',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('prontuario', sa.String(length=20), nullable=False),
    sa.Column('lmp_date', sa.Date(), nullable=False),
    sa.Column('edd', sa.Date(), nullable=False),
    sa.Column('current_week', sa.SmallInteger(), nullable=True),
    sa.Column('height_cm', sa.String(length=10), nullable=True),
    sa.Column('weight_initial_kg', sa.String(length=10), nullable=True),
    sa.Column('imc', sa.String(length=10), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risklevel'), nullable=True),
    sa.Column('acompanhante', sa.String(length=255), nullable=True),
    sa.Column('hospital', sa.String(length=255), nullable=True),
    sa.Column('number_of_fetuses', sa.SmallInteger(), nullable=True),
    sa.Column('parity', sa.String(length=10), nullable=True),
    sa.Column('cesarean_predicted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prontuario'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('secretaries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('appointments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'completed', 'cancelled', name='appointmentstatus'), nullable=True),
    sa.Column('patient_status', sa.Enum('pending', 'confirmed', 'reschedule_requested', 'reschedule_approved', name='patientappointmentstatus'), nullable=True),
    sa.Column('type', sa.Enum('routine', 'ultrasound', 'lab', 'follow_up', 'emergency', name='appointmenttype'), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reschedule_reason', sa.String(length=255), nullable=True),
    sa.Column('reschedule_observation', sa.Text(), nullable=True),
    sa.Column('reschedule_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reschedule_requested_by', sa.UUID(), nullable=True),
    sa.Column('reschedule_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reschedule_approved_by', sa.UUID(), nullable=True),
    sa.Column('new_date', sa.Date(), nullable=True),
    sa.Column('new_time', sa.Time(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reschedule_approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reschedule_requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_pressure_readings',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('systolic', sa.SmallInteger(), nullable=False),
    sa.Column('diastolic', sa.SmallInteger(), nullable=False),
    sa.Column('pulse_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('moment', sa.Enum('morning', 'afternoon', 'evening', 'night', name='timeofday'), nullable=False),
    sa.Column('classification', sa.Enum('Normal', 'Atenção', 'Alto', name='vitalclassification'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contractions',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.SmallInteger(), nullable=False),
    sa.Column('interval_minutes', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glucose_readings',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('value_mg_dl', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('moment', sa.Enum('fasting', 'after_meal', 'random', name='glucosemoment'), nullable=False),
    sa.Column('classification', sa.Enum('Normal', 'Atenção', 'Alto', name='vitalclassification'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ultrasounds',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('obstetric', 'morphology', 'detailed', name='ultrasoundtype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ig_weeks', sa.SmallInteger(), nullable=False),
    sa.Column('presentation', sa.Enum('cephalic', 'breech', 'transverse', name='fetalpresentation'), nullable=True),
    sa.Column('placenta_location', sa.String(length=100), nullable=True),
    sa.Column('amniotic_fluid_ml', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('fetal_heart_rate', sa.SmallInteger(), nullable=True),
    sa.Column('fetal_weight_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('percentile', sa.SmallInteger(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccines',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('vaccine_type', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('dose_number', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'missed', name='vaccinestatus'), nullable=True),
    sa.Column('reactions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccines')
    op.drop_table('ultrasounds')
    op.drop_table('glucose_readings')
    op.drop_table('contractions')
    op.drop_table('blood_pressure_readings')
    op.drop_table('appointments')
    op.drop_table('secretaries')
    op.drop_table('patients')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('clinics')
    # ### end Alembic commands ###
